version: "3"
services:
  selenium-lab:
    container_name: selenium-lab
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"