version: "3"
services:
  neo4j-lab:
    container_name: neo4j-lab
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    depends_on:
      - neo4j
    networks:
      - neo4jnet

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/pass1234"
      NEO4J_server_memory_heap_max__size: "8gb"
    restart: always
    networks:
      - neo4jnet

networks:
  neo4jnet:
    driver: bridge
